name: '@jscutlery/devkit CI'

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn nx affected --base=last-release --target=lint
      - run: yarn nx affected --base=last-release --target=build
      - run: yarn nx affected --base=last-release --target=test
      - run: yarn nx affected --base=last-release --target=e2e --headless

  release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs: [test]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Setup git user to "🤖 JSCutlery Bot"
        run: git config user.email "-" && git config user.name "🤖 JSCutlery Bot"
      - name: Version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        # Use npx instead of yarn because yarn automagically sets NPM_* environment variables
        # like NPM_CONFIG_REGISTRY so npm publish ends up ignoring the .npmrc file
        # which is set up by `setup-node` action.
        run: npx nx affected --base=last-release --target=version
      - name: Tag last-release
        run: git tag -f last-release
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true
